id: AF29FFB72
title: A Prayer to Dilgo Khyentse Rinpoche
type: translation
pechas:
- I30841BDC
- IE8808195
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:37:56.924409
  last_modified_at: 2023-01-04 11:37:56.924422
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I30841BDC/347D: 9CFE
  IE8808195/68CB: 9CFE
